# Model arguments
model_name_or_path: /scratch/ssd004/scratch/snajafi/model-weights/llama3.2-1b-sftdatasetv3-sft-checkpoint-111000
torch_dtype: bfloat16
model_revision: main
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_r: 64
lora_alpha: 64
lora_dropout: 0.01
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj
lora_modules_to_save:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj

# Data training arguments
# dataset_mixer:
#   /home/saeednjf/nearline/rrg-afyshe/datasets/llama-3.2-1b-offline-preference-data: 1.0
# dataset_splits:
# - train
# - test
# preprocessing_num_workers: 8

# DPOTrainer arguments
max_grad_norm: 1.0
bf16: true
beta: 0.0
do_eval: true
eval_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 16
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
dataset_num_proc: 128
loss_type: sigmoid
objective_type: dpo
average_logps: no
learning_rate: 10
output_dir: dummy
run_name: dummy
optim: adamw_8bit
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 500
save_total_limit: 1
seed: 42
warmup_ratio: 0.1