# Model arguments
model_name_or_path: dummy # we use this script for the 135M model too
model_revision: main
tokenizer_name_or_path: dummy # Custom tokenizer with <|im_start|> and <|im_end|> tokens
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  HuggingFaceTB/smol-smoltalk: 1.0

dataset_splits:
- train
- test

preprocessing_num_workers: 16

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: epoch
gradient_accumulation_steps: 4
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: dummy
hub_strategy: every_save
learning_rate: 1.0e-03
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 2
output_dir: dummy
run_name: dummy
optim: adamw_8bit
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
remove_unused_columns: true
report_to:
  - wandb
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1