# Model arguments
model_name_or_path: /work/saeed/narval/llama3.2-1b-sftdatasetv3-sft-checkpoint-111000
torch_dtype: bfloat16
model_revision: main
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: True
load_in_4bit: false
lora_r: 64
lora_alpha: 64
lora_dropout: 0.01
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
- gate_proj
- up_proj
- down_proj


dataset_mixer:
  /work/saeed/narval/llama-3.2-1b-offline-preference-data/dataset: 1.0

dataset_splits:
- train
- test

preprocessing_num_workers: 16

# DPOTrainer arguments
bf16: true
beta: 0.0
mmpo_reward_epsilon: 1.0
mmpo_relu_coefficient: 1.0
mmpo_relu_epsilon: 0.5
do_eval: true
eval_strategy: steps
eval_steps: 64
gradient_accumulation_steps: 16
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-6
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 2312
max_prompt_length: 1800
num_train_epochs: 3
dataset_num_proc: 16
loss_type: sigmoid
objective_type: mmpo
average_logps: no
optim: adamw_8bit
output_dir: dummy
run_name: dummy
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 64
save_total_limit: 2
seed: 42
warmup_ratio: 0.1