# Model arguments
model_name_or_path: /work/saeed/narval/llama3.2-1b-sftdatasetv3-sft-checkpoint-111000
torch_dtype: bfloat16
model_revision: main
attn_implementation: flash_attention_2

# LoRA arguments
use_peft: true
load_in_4bit: false
lora_r: 64
lora_alpha: 64
lora_dropout: 0.01
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj
# - gate_proj
# - up_proj
# - down_proj

# Data training arguments
# dataset_mixer:
#   /home/saeednjf/nearline/rrg-afyshe/datasets/llama-3.2-1b-offline-preference-data: 1.0
# dataset_splits:
# - train
# - test
# preprocessing_num_workers: 8

# DPOTrainer arguments
max_grad_norm: 1.0
bf16: true
beta: 0.0
do_eval: true
eval_strategy: steps
eval_steps: 50
gradient_accumulation_steps: 4
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_length: 6144
max_prompt_length: 2048
max_completion_length: 4096
num_train_epochs: 5
dataset_num_proc: 128
loss_type: sigmoid
objective_type: dpo
average_logps: no
learning_rate: 10
output_dir: dummy
run_name: dummy
optim: adamw_8bit
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 50
save_total_limit: 20
seed: 42
warmup_ratio: 0.01